//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity.Domain.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityCommonMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityCommonMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Identity.Domain.Resources.IdentityCommonMessages", typeof(IdentityCommonMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string FullNameEmpty {
            get {
                return ResourceManager.GetString("FullNameEmpty", resourceCulture);
            }
        }
        
        public static string FullNameInvalid {
            get {
                return ResourceManager.GetString("FullNameInvalid", resourceCulture);
            }
        }
        
        public static string FullNameInvalidLength {
            get {
                return ResourceManager.GetString("FullNameInvalidLength", resourceCulture);
            }
        }
        
        public static string UserIdIsRequired {
            get {
                return ResourceManager.GetString("UserIdIsRequired", resourceCulture);
            }
        }
        
        public static string WorkspaceIdIsRequired {
            get {
                return ResourceManager.GetString("WorkspaceIdIsRequired", resourceCulture);
            }
        }
        
        public static string UserAlreadyHasRole {
            get {
                return ResourceManager.GetString("UserAlreadyHasRole", resourceCulture);
            }
        }
        
        public static string UserAlreadyInactiveInWorkspace {
            get {
                return ResourceManager.GetString("UserAlreadyInactiveInWorkspace", resourceCulture);
            }
        }
        
        public static string UserAlreadyActiveInWorkspace {
            get {
                return ResourceManager.GetString("UserAlreadyActiveInWorkspace", resourceCulture);
            }
        }
        
        public static string WorkspaceMaxUsersMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("WorkspaceMaxUsersMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        public static string WorkspaceAlreadyInactive {
            get {
                return ResourceManager.GetString("WorkspaceAlreadyInactive", resourceCulture);
            }
        }
        
        public static string AuthenticationIdentifierIsRequired {
            get {
                return ResourceManager.GetString("AuthenticationIdentifierIsRequired", resourceCulture);
            }
        }
        
        public static string InvitationExpirationDaysExceeded {
            get {
                return ResourceManager.GetString("InvitationExpirationDaysExceeded", resourceCulture);
            }
        }
    }
}
